---
# tasks file for config_spine

- name: ENABLE NECESSARY FEATURES
  nxos_feature:
    feature: "{{ item.feature }}"
  with_items: "{{ features }}"

- name: ENABLE NV OVERLAY EVPN
  nxos_evpn_global:
    nv_overlay_evpn: true

- name: CONFIGURE ETHERNET INTERFACES AS L3
  nxos_interface:
    name: "{{ item.interface }}"
    description: "{{ item.description }}"
    mode: layer3
    mtu: 9216
  with_items:
    - "{{ l3_interfaces }}"

- name: CONFIGURE LOOPBACK INTERFACES AS L3
  nxos_interface:
    name: "{{ item.interface }}"
    description: "{{ item.description }}"
    mode: layer3
  with_items:
    - "{{ loopback_interfaces }}"

- name: ADD IP ADDRESSES TO LOOPBACK INTERFACES
  nxos_l3_interface:
    name: "{{ item.interface }}"
    ipv4: "{{ item.ipv4 }}"
    state: present
  with_items:
    - "{{ loopback_interfaces }}"

- name: ENABLE OSPF
  nxos_ospf:
    ospf: "{{ ospf_proc_id }}"
    state: present

- name: ADD L3 INTERFACES TO OSPF
  nxos_interface_ospf:
    interface: "{{ item.interface }}"
    ospf: "{{ ospf_proc_id }}"
    area: "{{ ospf_area }}"
  with_items:
    - "{{ ospf_loopback }}"
    - "{{ ospf_unnumbered_interfaces }}"

- name: MAKE LEAF-SPINE DOWNLINK INTERFACES OSPF POINT-TO-POINT NETWORKS
  nxos_config:
    lines: 
      - medium p2p
      - ip ospf network point-to-point
      - ip unnumbered loopback0
    parents: 
      - interface {{ ospf_unnumbered_interfaces }}
  with_items:
    - "{{ ospf_unnumbered_interfaces }}"

- name: ADD PIM SPARSE MODE TO INTERFACES
  nxos_pim_interface:
    interface: "{{ item.interface }}"
    sparse: yes
  with_items:
    - "{{ pim_interfaces }}"

- name: CONFIGURE ANYCAST RP ADDRESS
  nxos_pim_rp_address:
    rp_address: "{{ pim_rp_address }}"
    group_list: "{{ pim_group_list }}"

- name: CONFIGURE PIM SSM RANGE
  nxos_pim:
    ssm_range: "{{ pim_ssm_range }}"

- name: CONFIGURE ANYCAST RP 100.1.1.1 10.1.1.1
  nxos_config:
    lines: 
      - ip pim anycast-rp 100.1.1.1 10.1.1.1
      - ip pim anycast-rp 100.1.1.1 20.1.1.1
    save_when: modified

- name: ENSURE BGP ASN EXISTS
  nxos_bgp:
    asn: "{{ bgp_asn }}"
    router_id: "{{ bgp_router_id }}"
  tags:
    - bgp

- name: BGP NEIGHBOR CONFIG
  nxos_bgp_neighbor:
    asn: "{{ bgp_asn }}"
    neighbor: "{{ item.neighbor }}"
    remote_as: "{{ item.remote_as }}"
    update_source: "Loopback0"
  with_items: "{{ bgp_neighbors }}"
  tags:
    - bgp

- name: CONFIGURE L2VPN UNICAST ADDRESS FAMILY
  nxos_bgp_neighbor_af:
    asn: "{{ bgp_asn }}"
    neighbor: "{{ item.neighbor }}"
    afi: l2vpn
    safi: evpn
    send_community: both
    route_reflector_client: true
  with_items: "{{ bgp_neighbors }}"
  tags:
    - bgp
