---
mgmt_interface:
  - { interface: "mgmt0", description: "MTGT SWITCH Ethernet2", ipv4: "192.168.122.22/24" }

l2_interfaces:
  - { interface: "Ethernet2/1", description: "Server facing Interfaces", mode: "access", access_vlan: "1002" }
  - { interface: "Ethernet2/2", description: "Server facing Interfaces", mode: "access", access_vlan: "1001" }

l3_interfaces:
  - { interface: "Loopback0", description: "Loopback0 for local VTEP IP, and BGP", ipv4: "40.1.1.1/32" }
  - { interface: "Ethernet2/14", description: "Spine-leaf interconnect spine01", ipv4: "192.168.2.22/24" }
  - { interface: "Ethernet2/15", description: "Spine-leaf interconnect spine02", ipv4: "192.168.4.23/24" }
  - { interface: "Vlan1001", description: "Server facing SVI", ipv4: "4.1.1.1/24", ipv6: "4:1:0:1::1/64" }
  - { interface: "Vlan1002", description: "Server facing SVI", ipv4: "4.2.2.1/24", ipv6: "4:2:0:1::1/64" }

anycast_gw_interfaces:
  - { interface: "Vlan1001" }
  - { interface: "Vlan1002" }
