---
mgmt_interface:
  - { interface: "mgmt0", description: "MTGT SWITCH Ethernet2", addr: "192.168.122.22", mask: "32" }

l2_interfaces:
  - { interface: "Ethernet2/1", description: "", mode: "access", access_vlan: "1002" }
  - { interface: "Ethernet2/2", description: "", mode: "access", access_vlan: "1001" }

l3_interfaces:
  - { interface: "Loopback0", description: "Loopback0 for local VTEP IP, and BGP", addr: "40.1.1.1", mask: "32" }
  - { interface: "Ethernet2/14", description: "Spine-leaf interconnect spine01", addr: "192.168.2.22", mask: "24" }
  - { interface: "Ethernet2/15", description: "Spine-leaf interconnect spine02", addr: "192.168.4.23", mask: "24" }
  - { interface: "Vlan1001", description: "Server facing SVI", addr: "4.1.1.1", mask: "24" }
  - { interface: "Vlan1002", description: "Server facing SVI", addr: "4.2.2.1", mask: "24" }

