---
# tasks file for config_spine_interfaces

- name: CONFIGURE ETHERNET INTERFACES AS L3
  nxos_interface:
    name: "{{ item.interface }}"
    description: "{{ item.description }}"
    mode: layer3
    mtu: 9216
  with_items:
    - "{{ l3_interfaces }}"

- name: CONFIGURE LOOPBACK INTERFACES AS L3
  nxos_interface:
    name: "{{ item.interface }}"
    description: "{{ item.description }}"
    mode: layer3
  with_items:
    - "{{ loopback_interfaces }}"

- name: ADD IP ADDRESSES TO LOOPBACK INTERFACES
  nxos_l3_interface:
    name: "{{ item.interface }}"
    ipv4: "{{ item.ipv4 }}"
    state: present
  with_items:
    - "{{ loopback_interfaces }}"
