---
role: spine

bgp_asn: 65535
bgp_router_id: 10.1.1.1

bgp_address_families:
  - { afi: l2vpn, safi: evpn }

bgp_neighbors:
  - { remote_as: 65535, neighbor: 30.1.1.1, update_source: "loopback0", send_community: "both", rr_client: true }
  - { remote_as: 65535, neighbor: 40.1.1.1, update_source: "loopback0", send_community: "both", rr_client: true }

ospf_proc_id: 1
ospf_area: 0.0.0.0
ospf_interfaces:
  - "Loopback0"
  - "Loopback1"
  - "Ethernet2/1"
  - "Ethernet2/2"

# nxos_pim #
pim_ssm_range: "232.0.0.0"
pim_ssm_mask: "8"

# nxos_pim_rp_address #
pim_rp_address: "100.1.1.1"
pim_group-list: "224.0.0.0"
pim_group-list_mask: "4"

# nxos_pim_interface #
pim_interfaces:
  - "Loopback0"
  - "Loopback1"
  - "Ethernet2/1"
  - "Ethernet2/2"
