---
# tasks file for config_leaf

- name: CONFIGURE ETHERNET INTERFACES AS L3
  nxos_interface:
    name: "{{ item.interface }}"
    description: "{{ item.description }}"
    mode: layer3
    mtu: 9216
  with_items:
    - "{{ l3_interfaces }}"

- name: CONFIGURE LOOPBACK INTERFACES AS L3
  nxos_interface:
    name: "{{ item.interface }}"
    description: "{{ item.description }}"
    mode: layer3
  with_items:
    - "{{ loopback_interfaces }}"

- name: ADD IP ADDRESSES TO LOOPBACK INTERFACES
  nxos_l3_interface:
    name: "{{ item.interface }}"
    ipv4: "{{ item.ipv4 }}"
    state: present
  with_items:
    - "{{ loopback_interfaces }}"

- name: ENSURE VLANs 1,101,1001, and 1002 ARE PRESENT ON THE LEAF SWITCH
  nxos_vlan:
    vlan_range: "1,101,1001,1002"
    state: present

- name: CREATE VRF AND CONFIGURE VNI
  nxos_vrf:
    name: "{{ item.name }}"
    vni: "{{ item.vni }}"
    rd: "auto"
  with_items:
    - "{{ vrfs }}"

- name: ADD INTERFACES TO VRF
  nxos_config:
    lines: 
      - vrf member {{ item.name }}
    parents: interface {{ item.interfaces }}
    save_when: modified
  loop: "{{ vrfs }}"

- name: CREATE VRF AND CONFIGURE VNI IPV4
  nxos_vrf_af:
    vrf: "{{ item.name }}"
    route_target_both_auto_evpn: true
    afi: ipv4
  with_items:
    - "{{ vrfs }}"

- name: CREATE VRF AND CONFIGURE VNI IPV6
  nxos_vrf_af:
    vrf: "{{ item.name }}"
    route_target_both_auto_evpn: true
    afi: ipv6
  with_items:
    - "{{ vrfs }}"

- name: CREATE OVERLAY VRF VLAN AND VN-SEGMENT
  nxos_vlan:
    vlan_id: "{{ item.vlan_id }}"
    mapped_vni: "{{ item.mapped_vni }}"
  with_items:
    - "{{ vlan_mappings }}"

- name: CREATE OVERLAY VRF VLAN AND VN-SEGMENT
  nxos_config:
    lines:
      - vn-segment {{ item.mapped_vni }}
    parents:
      - vlan {{ item.vlan_id }}
  loop: "{{ vlan_mappings }}"
  tags:
    - mapped

- name: CONFIGURE LEAF SERVER INTERFACES AS L2
  nxos_interface:
    name: "{{ item.interface }}"
    description: "{{ item.description }}"
    mode: layer2
    mtu: 9216
  with_items:
    - "{{ l2_interfaces }}"

- name: ADD SERVER INTERFACES TO VLANs
  nxos_config:
    lines: 
      - switchport access vlan {{ item.access_vlan }}
    parents: interface {{ item.interface }}
    save_when: changed
  loop: "{{ l2_interfaces }}"
  ignore_errors: true

- name: ENABLE OSPF
  nxos_ospf:
    ospf: "{{ ospf_proc_id }}"
    state: present

- name: ADD L3 INTERFACES TO OSPF
  nxos_interface_ospf:
    interface: "{{ item.interface }}"
    ospf: "{{ ospf_proc_id }}"
    area: "{{ ospf_area }}"
  with_items:
    - "{{ ospf_loopback }}"
    - "{{ ospf_unnumbered_interfaces }}"

- name: MAKE LEAF-SPINE UPLINK INTERFACES OSPF POINT-TO-POINT NETWORKS
  nxos_config:
    lines: 
      - medium p2p
      - ip ospf network point-to-point
      - ip unnumbered loopback0
    parents: 
      - interface {{ item.interface }}
  with_items:
    - "{{ ospf_unnumbered_interfaces }}"

- name: ADD PIM SPARSE MODE TO INTERFACES
  nxos_pim_interface:
    interface: "{{ item.interface }}"
    sparse: yes
  with_items:
    - "{{ pim_interfaces }}"

- name: CONFIGURE ANYCAST RP ADDRESS
  nxos_pim_rp_address:
    rp_address: "{{ pim_rp_address }}"
    group_list: "{{ pim_group_list }}"

- name: CONFIGURE PIM SSM RANGE
  nxos_pim:
    ssm_range: "{{ pim_ssm_range }}"

- name: ASSIGN ANYCAST GATEWAY
  nxos_overlay_global:
    anycast_gateway_mac: "0000.2222.3333"

- name: CONFIGURE SVI INTERFACES AS ANYCAST GATEWAYS
  nxos_interface:
    name: "{{ item.interface }}"
    fabric_forwarding_anycast_gateway: yes
  with_items:
    - "{{ anycast_gw_interfaces }}"

- name: ENSURE BGP ASN EXISTS
  nxos_bgp:
    asn: "{{ bgp_asn }}"
    router_id: "{{ bgp_router_id }}"
  tags:
    - bgp

- name: BGP NEIGHBOR CONFIG
  nxos_bgp_neighbor:
    asn: "{{ bgp_asn }}"
    neighbor: "{{ item.neighbor }}"
    remote_as: "{{ item.remote_as }}"
    update_source: "Loopback0"
  with_items: "{{ bgp_neighbors }}"
  tags:
    - bgp

- name: CONFIGURE IPV4 UNICAST ADDRESS FAMILY
  nxos_bgp_neighbor_af:
    asn: "{{ bgp_asn }}"
    neighbor: "{{ item.neighbor }}"
    afi: ipv4
    safi: unicast
  with_items: "{{ bgp_neighbors }}"
  tags:
    - bgp

- name: CONFIGURE L2VPN UNICAST ADDRESS FAMILY
  nxos_bgp_neighbor_af:
    asn: "{{ bgp_asn }}"
    neighbor: "{{ item.neighbor }}"
    afi: l2vpn
    safi: evpn
    send_community: both
    route_reflector_client: true
  with_items: "{{ bgp_neighbors }}"
  tags:
    - bgp

- name: Create the network virtualization endpoint (NVE) interface
  nxos_vxlan_vtep:
    interface: nve1
    host_reachability: true
    source_interface: loopback0
  tags: nve

- name: ASSOCIATE NVE WITH VRF 
  nxos_vxlan_vtep_vni:
    interface: nve1
    ingress_replication: bgp
  tags: nve

- name: ASSOCIATE NVE WITH VRF 
  nxos_vxlan_vtep_vni:
    interface: nve1
    assoc_vrf: true
    vni: 900001
  tags: nve

- name: ASSOCIATE VNI 2001001 WITH NVE INTERFACE 
  nxos_vxlan_vtep_vni:
    interface: nve1
    multicast_group: 239.0.0.1
    vni: 2001001
  tags: nve

- name: ASSOCIATE VNI 2001002 WITH NVE INTERFACE 
  nxos_vxlan_vtep_vni:
    interface: nve1
    multicast_group: 239.0.0.1
    vni: 2001002
  tags: nve